DataFrame

In [1]:
import pandas as pd

In [3]:
df=pd.DataFrame()
type(df)

pandas.DataFrame

In [5]:
df=pd.DataFrame([[101,'Manisha',60000],[102,'Sarang',50000],[103,'sanvi',40000]],columns=('ID','NAME','SAL'))
df

    ID     NAME    SAL
0  101  Manisha  60000
1  102   Sarang  50000
2  103    sanvi  40000

In [6]:
df.set_index('ID')

        NAME    SAL
ID
101  Manisha  60000
102   Sarang  50000
103    sanvi  40000

In [7]:
df['NAME']

0    Manisha
1     Sarang
2      sanvi
Name: NAME, dtype: str

In [9]:
df2=pd.DataFrame({'ID':[101,102,103],
                  'name':['Manisha','kapil','shubhi'],
                  'SAL':[70000,80000,90000]})
df2

    ID     name    SAL
0  101  Manisha  70000
1  102    kapil  80000
2  103   shubhi  90000

In [13]:
df3.df.set_index('ID')

NameError: name 'df3' is not defined

In [14]:
df3

NameError: name 'df3' is not defined

In [15]:
iris=pd.read_csv("C:/Users/Hajapure/OneDrive/Desktop/Data analysis/Data set/Iris.csv.xls")
iris

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [16]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [17]:
iris.tail()

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [18]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [19]:
iris.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [21]:
iris['Sepal_Length'].mean()

np.float64(5.843333333333334)

In [22]:
iris['Species'].unique()

<StringArray>
['Setosa', 'Versicolor', 'Virginica']
Length: 3, dtype: str

In [23]:
iris['Species'].value_counts()

Species
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [24]:
iris['Species'].min()

'Setosa'

In [25]:
iris['Species'].max()

'Virginica'

In [27]:
iris.drop('Species',axis=1,inplace=True)

In [28]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [29]:
iris.drop(0,inplace=True)

In [30]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4

In [32]:
df['Address']=['Pune','Mumbai','Nanded']

In [33]:
df

    ID     NAME    SAL Address
0  101  Manisha  60000    Pune
1  102   Sarang  50000  Mumbai
2  103    sanvi  40000  Nanded

In [34]:
df.loc[3]=[104,'SHIVANSH',40000,'shelagaon']

In [35]:
df

    ID      NAME    SAL    Address
0  101   Manisha  60000       Pune
1  102    Sarang  50000     Mumbai
2  103     sanvi  40000     Nanded
3  104  SHIVANSH  40000  shelagaon