##StudentDataframe

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("C:/Users/Hajapure/OneDrive/Desktop/Data analysis/Data set/student_10.csv.xls")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [9]:
df.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [11]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [13]:
df['Class']==12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [14]:
df[df['Class']==12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [18]:
df[df['Percentage'] >50]

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [20]:
df['Student ID']==1008.0

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Student ID, dtype: bool

In [21]:
df[df['Student ID']==1008.0]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [25]:
df.loc[df['Student ID']==1008.0,'Percentage']=92
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        92.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

##Concate

In [27]:
df1=pd.DataFrame({'id':[101,102,103], 'Name':['Manisha','Mahadevi','Shivam']})
df1

    id      Name
0  101   Manisha
1  102  Mahadevi
2  103    Shivam

In [29]:
df2=pd.DataFrame({'dept_id':[1,2,1], 'dname':['Admin','IT','Admin']})
df2

   dept_id  dname
0        1  Admin
1        2     IT
2        1  Admin

In [30]:
pd.concat([df1,df2],axis=1)

    id      Name  dept_id  dname
0  101   Manisha        1  Admin
1  102  Mahadevi        2     IT
2  103    Shivam        1  Admin

In [31]:
pd.concat([df1,df2])

      id      Name  dept_id  dname
0  101.0   Manisha      NaN    NaN
1  102.0  Mahadevi      NaN    NaN
2  103.0    Shivam      NaN    NaN
0    NaN       NaN      1.0  Admin
1    NaN       NaN      2.0     IT
2    NaN       NaN      1.0  Admin

Merge

In [32]:
emp=pd.DataFrame({'id':[101,102,103,104], 'name':['Aakash','Rohit','Kapil','Govinda'], 'did':[1,2,3,4]})
emp

    id     name  did
0  101   Aakash    1
1  102    Rohit    2
2  103    Kapil    3
3  104  Govinda    4

In [34]:
dept=pd.DataFrame({'did':[1,2,3],'dname':['IT','Admin','Sales']})
dept

   did  dname
0    1     IT
1    2  Admin
2    3  Sales

In [36]:
pd.merge(emp,dept,how='inner')

    id    name  did  dname
0  101  Aakash    1     IT
1  102   Rohit    2  Admin
2  103   Kapil    3  Sales

In [37]:
pd.merge(emp,dept,how='left')

    id     name  did  dname
0  101   Aakash    1     IT
1  102    Rohit    2  Admin
2  103    Kapil    3  Sales
3  104  Govinda    4    NaN

In [38]:
pd.merge(emp,dept,how='right')

    id    name  did  dname
0  101  Aakash    1     IT
1  102   Rohit    2  Admin
2  103   Kapil    3  Sales

In [43]:
pd.merge(emp, dept, how='inner', on='dept_id')

KeyError: 'dept_id'

In [2]:
df.head()

NameError: name 'df' is not defined